[workspace]
authors = ["ken <hidden@a.com>"]
channels = ["conda-forge"]
name = "download img"
platforms = ["win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
openpyxl = ">=3.1.5,<4"
requests = ">=2.32.4,<3"
pillow = ">=11.3.0,<12"
httpx = ">=0.28.1,<0.29"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
httpx-retries = ">=0.4.0, <0.5"
